source: org-working-set.el
package: org-working-set
required_pieces_commentary:
  - Purpose
  - Similar Packages
  - Setup
  - User-Story
pieces_for_docstring:
  - Purpose
  - Similar Packages
  - User-Story
testfile: owst.el
# Maybe override this in rake_config_no_git.yml
rake_be_symlink: false

